const chat=document.getElementById("chat"),input=document.getElementById("message"),send=document.getElementById("send"),welcome=document.getElementById("welcome"),history=document.getElementById("history"),historySearch=document.getElementById("historySearch"),clearHistory=document.getElementById("clearHistory");let chats=JSON.parse(localStorage.getItem("aiChats")||"[]"),persona=localStorage.getItem("aiPersona")||"Friendly",theme=localStorage.getItem("aiTheme")||"dark";document.body.className=theme;document.getElementById("personaBtn").textContent="🤖 "+persona;
function addMessage(text,type){welcome.style.display="none";const row=document.createElement("div");row.className="msg "+type;if(type==="bot"){const av=document.createElement("div");av.className="mini-avatar";av.textContent="✦";row.appendChild(av)}const content=document.createElement("div");content.className="message-content";const name=document.createElement("div");name.className="message-name";name.textContent=type==="user"?"You":"AI Companion";content.appendChild(name);const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=text;content.appendChild(bubble);const actions=document.createElement("div");actions.className="message-actions";const copy=document.createElement("button");copy.textContent="Copy";copy.onclick=()=>navigator.clipboard?.writeText(text);actions.appendChild(copy);if(type==="bot"){const regen=document.createElement("button");regen.textContent="Regenerate";regen.onclick=()=>reply();actions.appendChild(regen)}content.appendChild(actions);row.appendChild(content);chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
function showTyping(){const row=document.createElement("div");row.className="msg bot";row.id="typing";const av=document.createElement("div");av.className="mini-avatar";av.textContent="✦";const content=document.createElement("div");content.className="message-content";content.innerHTML='<div class="message-name">AI Companion</div><div class="bubble typing"><span></span><span></span><span></span></div>';row.append(av,content);chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
function removeTyping(){document.getElementById("typing")?.remove()}function save(){localStorage.setItem("aiChats",JSON.stringify(chats.slice(0,30)))}
function renderHistory(filter=""){history.innerHTML="";const q=filter.trim().toLowerCase();chats.slice(0,30).forEach((t,i)=>{const pinned=t.startsWith("📌 "),archived=t.startsWith("🗄 "),title=t.replace(/^(📌 |🗄 )/,"");if(q&&!title.toLowerCase().includes(q))return;const item=document.createElement("div");item.className="history-item";const b=document.createElement("button");b.className="history-main";b.textContent=(pinned?"📌 ":archived?"🗄 ":"")+title;b.onclick=()=>{input.value=title;input.focus()};const more=document.createElement("button");more.className="history-more";more.textContent="⋯";const menu=document.createElement("div");menu.className="history-menu";menu.innerHTML='<button data-action="pin">'+(pinned?"📌 Unpin":"📌 Pin")+'</button><button data-action="share">↗ Share</button><button data-action="rename">✎ Rename</button><button data-action="archive">'+(archived?"▣ Unarchive":"▣ Archive")+'</button><button data-action="delete" class="danger">⌫ Delete</button>';more.onclick=e=>{e.stopPropagation();document.querySelectorAll(".history-menu.open").forEach(m=>m!==menu&&m.classList.remove("open"));menu.classList.toggle("open")};menu.querySelectorAll("button").forEach(action=>action.onclick=e=>{e.stopPropagation();const a=action.dataset.action;if(a==="delete"){chats.splice(i,1);save();renderHistory(historySearch.value)}else if(a==="rename"){const n=prompt("Rename conversation:",title);if(n?.trim()){chats[i]=(pinned?"📌 ":"")+(archived?"🗄 ":"")+n.trim();save();renderHistory(historySearch.value)}}else if(a==="pin"){chats[i]=pinned?title:"📌 "+title;save();renderHistory(historySearch.value)}else if(a==="archive"){chats[i]=archived?title:"🗄 "+title;save();renderHistory(historySearch.value)}else if(a==="share"){navigator.clipboard?.writeText(title);alert("Conversation title copied. Full sharing will be connected with the backend later.")}menu.classList.remove("open")});item.append(b,more,menu);history.appendChild(item)})}
historySearch.oninput=()=>renderHistory(historySearch.value);clearHistory.onclick=()=>{if(chats.length&&confirm("Delete all conversations? This cannot be undone.")){chats=[];save();renderHistory()}};
document.addEventListener("click",()=>document.querySelectorAll(".history-menu.open").forEach(m=>m.classList.remove("open")));
function reply(){showTyping();const replies={Friendly:"Sure! I’m ready to help. Tell me what you’d like to do next.",Professional:"Understood. I can help you organize this into clear, practical steps.",Tutor:"Absolutely. Let’s break it down step by step so it’s easy to understand.",Creative:"Let’s make it interesting. I can help turn that idea into something creative.",Coding:"I can help you plan, debug, or build the code. Give me the details."};setTimeout(()=>{removeTyping();addMessage(replies[persona],"bot")},650)}
function submit(){const text=input.value.trim();if(!text)return;addMessage(text,"user");chats.unshift(text);save();renderHistory(historySearch.value);input.value="";input.style.height="auto";reply()}
send.onclick=submit;input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,150)+"px"});document.querySelectorAll(".suggestions button").forEach(b=>b.onclick=()=>{input.value=b.dataset.msg;submit()});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();historySearch.focus();historySearch.select()}if(e.key==="Escape"){document.querySelectorAll(".history-menu.open").forEach(m=>m.classList.remove("open"));document.getElementById("profileModal").classList.remove("open")}});
document.getElementById("newChat").onclick=()=>{chat.innerHTML="";chat.appendChild(welcome);welcome.style.display="block";input.value="";input.focus()};document.getElementById("mobileMenu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");document.getElementById("attach").onclick=()=>document.getElementById("fileInput").click();document.getElementById("fileInput").onchange=e=>{const f=e.target.files[0];if(f)document.getElementById("filePreview").textContent="📎 "+f.name+" • "+Math.max(1,Math.round(f.size/1024))+" KB"};
const voiceBtn=document.getElementById("voice"),voiceStatus=document.getElementById("voiceStatus");let recognition=null,listening=false;voiceBtn.onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){voiceStatus.textContent="Voice input is not supported in this browser.";return}if(listening){recognition?.stop();return}recognition=new R();recognition.lang="en-US";recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{listening=true;voiceBtn.classList.add("recording");voiceStatus.textContent="Listening…"};recognition.onresult=e=>{let finalText="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)finalText+=e.results[i][0].transcript;if(finalText){input.value+=(input.value?" ":"")+finalText;input.dispatchEvent(new Event("input"));input.focus()}};recognition.onerror=()=>voiceStatus.textContent="Voice input ended.";recognition.onend=()=>{listening=false;voiceBtn.classList.remove("recording");setTimeout(()=>voiceStatus.textContent="",1200)};recognition.start()};
const modal=document.getElementById("modal"),personaSel=document.getElementById("persona"),themeSel=document.getElementById("theme");personaSel.value=persona;themeSel.value=theme;document.getElementById("settingsBtn").onclick=()=>modal.classList.add("open");document.getElementById("personaBtn").onclick=()=>modal.classList.add("open");document.getElementById("closeModal").onclick=()=>modal.classList.remove("open");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")};document.getElementById("saveSettings").onclick=()=>{persona=personaSel.value;theme=themeSel.value;localStorage.setItem("aiPersona",persona);localStorage.setItem("aiTheme",theme);document.body.className=theme;document.getElementById("personaBtn").textContent="🤖 "+persona;refreshProfile();modal.classList.remove("open")};document.getElementById("themeBtn").onclick=()=>{theme=theme==="dark"?"light":theme==="light"?"amoled":"dark";document.body.className=theme;localStorage.setItem("aiTheme",theme);themeSel.value=theme;refreshProfile()};document.getElementById("exportBtn").onclick=()=>{const text=chats.map((x,i)=>(i+1)+". "+x).join("\n\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text||"No messages yet."],{type:"text/plain"}));a.download="ai-companion-chat.txt";a.click();URL.revokeObjectURL(a.href)};
const sidebarProfile=document.getElementById("sidebarProfile"),profilePopover=document.getElementById("profilePopover"),sidebarAuth=document.getElementById("sidebarAuth");
function updateSidebarAccount(){const logged=localStorage.getItem("aiLoggedIn")==="true",name=localStorage.getItem("aiProfileName")||"AI User";document.getElementById("popoverName").textContent=name;document.getElementById("popoverAvatar").textContent=name.slice(0,2).toUpperCase();sidebarAuth.textContent=logged?"↪ Log out":"↪ Log in"}
sidebarProfile.onclick=e=>{e.stopPropagation();updateSidebarAccount();profilePopover.classList.toggle("open")};
sidebarAuth.onclick=e=>{e.stopPropagation();if(localStorage.getItem("aiLoggedIn")==="true"){localStorage.removeItem("aiLoggedIn");sidebarAuth.textContent="↪ Log in"}else location.href="pages/login.html";profilePopover.classList.remove("open")};
document.addEventListener("click",e=>{if(!profilePopover.contains(e.target)&&e.target!==sidebarProfile)profilePopover.classList.remove("open")});
updateSidebarAccount();
const modal=document.getElementById("modal"),personaSel=document.getElementById("persona"),themeSel=document.getElementById("theme");personaSel.value=persona;themeSel.value=theme;
document.getElementById("settingsBtn").onclick=()=>modal.classList.add("open");document.getElementById("personaBtn").onclick=()=>modal.classList.add("open");document.getElementById("closeModal").onclick=()=>modal.classList.remove("open");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")};
document.getElementById("saveSettings").onclick=()=>{persona=personaSel.value;theme=themeSel.value;localStorage.setItem("aiPersona",persona);localStorage.setItem("aiTheme",theme);document.body.className=theme;document.getElementById("personaBtn").textContent="🤖 "+persona;modal.classList.remove("open")};
document.getElementById("themeBtn").onclick=()=>{theme=theme==="dark"?"light":theme==="light"?"amoled":"dark";document.body.className=theme;localStorage.setItem("aiTheme",theme);themeSel.value=theme};
document.getElementById("exportBtn").onclick=()=>{const text=chats.map((x,i)=>(i+1)+". "+x).join("\n\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text||"No messages yet."],{type:"text/plain"}));a.download="ai-companion-chat.txt";a.click();URL.revokeObjectURL(a.href)};
