const chat=document.getElementById("chat"),input=document.getElementById("message"),send=document.getElementById("send"),welcome=document.getElementById("welcome"),history=document.getElementById("history");let chats=JSON.parse(localStorage.getItem("aiChats")||"[]"),persona=localStorage.getItem("aiPersona")||"Friendly",theme=localStorage.getItem("aiTheme")||"dark";document.body.classList.add(theme);document.getElementById("personaBtn").textContent="🤖 "+persona;
function addMessage(text,type){welcome.style.display="none";const row=document.createElement("div");row.className="msg "+type;const b=document.createElement("div");b.className="bubble";b.textContent=text;row.appendChild(b);chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
function renderHistory(){history.innerHTML="";chats.slice(0,10).forEach((t,i)=>{const b=document.createElement("button");b.textContent=t;b.onclick=()=>{input.value=t;input.focus()};history.appendChild(b)})}
function save(){localStorage.setItem("aiChats",JSON.stringify(chats.slice(0,30)))}
function reply(){const replies={Friendly:"Sure! I’m ready to help. Tell me what you’d like to do next.",Professional:"Understood. I can help you organize this into clear, practical steps.",Tutor:"Absolutely. Let’s break it down step by step so it’s easy to understand.",Creative:"Let’s make it interesting. I can help turn that idea into something creative.",Coding:"I can help you plan, debug, or build the code. Give me the details."};setTimeout(()=>addMessage(replies[persona],"bot"),350)}
function submit(){const text=input.value.trim();if(!text)return;addMessage(text,"user");chats.unshift(text);save();renderHistory();input.value="";input.style.height="auto";reply()}
send.onclick=submit;input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,140)+"px"});document.querySelectorAll(".suggestions button").forEach(b=>b.onclick=()=>{input.value=b.dataset.msg;submit()});
document.getElementById("newChat").onclick=()=>{chat.innerHTML="";chat.appendChild(welcome);welcome.style.display="block";input.value=""};
document.getElementById("mobileMenu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
document.getElementById("attach").onclick=()=>document.getElementById("fileInput").click();
document.getElementById("fileInput").onchange=e=>{const f=e.target.files[0];if(f)document.getElementById("filePreview").textContent="📎 "+f.name+" • "+Math.round(f.size/1024)+" KB"};
document.getElementById("voice").onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){input.placeholder="Voice input is not supported here.";return}const r=new R();r.lang="en-US";r.onresult=e=>{input.value=e.results[0][0].transcript;input.dispatchEvent(new Event("input"))};r.start()};
const modal=document.getElementById("modal"),personaSel=document.getElementById("persona"),themeSel=document.getElementById("theme");personaSel.value=persona;themeSel.value=theme;
document.getElementById("settingsBtn").onclick=()=>modal.classList.add("open");document.getElementById("personaBtn").onclick=()=>modal.classList.add("open");document.getElementById("closeModal").onclick=()=>modal.classList.remove("open");document.getElementById("saveSettings").onclick=()=>{persona=personaSel.value;theme=themeSel.value;localStorage.setItem("aiPersona",persona);localStorage.setItem("aiTheme",theme);document.body.className=theme;document.getElementById("personaBtn").textContent="🤖 "+persona;modal.classList.remove("open")};
document.getElementById("themeBtn").onclick=()=>{theme=theme==="dark"?"light":theme==="light"?"amoled":"dark";document.body.className=theme;localStorage.setItem("aiTheme",theme);themeSel.value=theme};
document.getElementById("exportBtn").onclick=()=>{const text=chats.map((x,i)=>(i+1)+". "+x).join("\n\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text||"No messages yet."],{type:"text/plain"}));a.download="ai-companion-chat.txt";a.click();URL.revokeObjectURL(a.href)};
renderHistory();