const $=id=>document.getElementById(id);
const chat=$("chat"),input=$("message"),history=$("history"),search=$("historySearch");
let chats=JSON.parse(localStorage.getItem("aiChats")||"[]"),persona=localStorage.getItem("aiPersona")||"Friendly",theme=localStorage.getItem("aiTheme")||"dark";
function save(){localStorage.setItem("aiChats",JSON.stringify(chats.slice(0,30)))}
function addMessage(text,type){$("welcome").style.display="none";const row=document.createElement("div");row.className="msg "+type;if(type==="bot"){const a=document.createElement("div");a.className="mini-avatar";a.textContent="✦";row.appendChild(a)}const c=document.createElement("div");c.className="message-content";const n=document.createElement("div");n.className="message-name";n.textContent=type==="user"?"You":"AI Companion";const b=document.createElement("div");b.className="bubble";b.textContent=text;c.append(n,b);row.appendChild(c);chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
function renderHistory(q=""){history.innerHTML="";chats.slice(0,30).forEach((t,i)=>{const pinned=t.startsWith("📌 "),title=t.replace(/^📌 /,""),item=document.createElement("div");item.className="history-item";const b=document.createElement("button");b.className="history-main";b.textContent=(pinned?"📌 ":"")+title;b.onclick=()=>{input.value=title;input.focus()};const more=document.createElement("button");more.className="history-more";more.textContent="⋯";const menu=document.createElement("div");menu.className="history-menu";menu.innerHTML='<button>📌 '+(pinned?"Unpin":"Pin")+'</button><button>✎ Rename</button><button>⌫ Delete</button>';more.onclick=e=>{e.stopPropagation();menu.classList.toggle("open")};menu.children[0].onclick=()=>{chats[i]=pinned?title:"📌 "+title;save();renderHistory(search.value)};menu.children[1].onclick=()=>{const n=prompt("Rename conversation:",title);if(n?.trim()){chats[i]=(pinned?"📌 ":"")+n.trim();save();renderHistory(search.value)}};menu.children[2].onclick=()=>{chats.splice(i,1);save();renderHistory(search.value)};if(!q||title.toLowerCase().includes(q.toLowerCase())){item.append(b,more,menu);history.appendChild(item)}})}
function reply(){const row=document.createElement("div");row.className="msg bot";row.innerHTML='<div class="mini-avatar">✦</div><div class="message-content"><div class="message-name">AI Companion</div><div class="bubble typing"><span></span><span></span><span></span></div></div>';chat.appendChild(row);setTimeout(()=>{row.remove();const r={Friendly:"Sure! I’m ready to help. Tell me what you’d like to do next.",Professional:"Understood. I can help you organize this into clear steps.",Tutor:"Absolutely. Let’s break it down step by step.",Creative:"Let’s make it creative. Tell me your idea.",Coding:"I can help you plan, debug, or build the code."};addMessage(r[persona],"bot")},600)}
function submit(){const t=input.value.trim();if(!t)return;addMessage(t,"user");chats.unshift(t);save();renderHistory();input.value="";reply()}
$("send").onclick=submit;input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}};search.oninput=()=>renderHistory(search.value);$("clearHistory").onclick=()=>{if(confirm("Delete all conversations?")){chats=[];save();renderHistory()}};
$("newChat").onclick=()=>{chat.innerHTML="";chat.appendChild($("welcome"));$("welcome").style.display="block";input.value=""};
$("mobileMenu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
$("attach").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>{const f=e.target.files[0];if(f)$("filePreview").textContent="📎 "+f.name};
const modal=$("modal"),personaSel=$("persona"),themeSel=$("theme");function apply(){document.body.className=theme;$("personaBtn").textContent="🤖 "+persona;personaSel.value=persona;themeSel.value=theme}apply();
$("settingsBtn").onclick=()=>$("modal").classList.add("open");$("personaBtn").onclick=()=>$("modal").classList.add("open");$("closeModal").onclick=()=>$("modal").classList.remove("open");$("saveSettings").onclick=()=>{persona=personaSel.value;theme=themeSel.value;localStorage.setItem("aiPersona",persona);localStorage.setItem("aiTheme",theme);apply();modal.classList.remove("open")};$("themeBtn").onclick=()=>{theme=theme==="dark"?"light":theme==="light"?"amoled":"dark";localStorage.setItem("aiTheme",theme);apply()};
$("exportBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([chats.join("\n\n")],{type:"text/plain"}));a.download="ai-companion-chat.txt";a.click()};
const profile=$("sidebarProfile"),pop=$("profilePopover");function account(){const n=localStorage.getItem("aiProfileName")||"AI User";$("popoverName").textContent=n;$("popoverAvatar").textContent=n.slice(0,2).toUpperCase();$("sidebarProfileName").textContent=n;$("sidebarAvatarText").textContent=n.slice(0,2).toUpperCase();$("sidebarAuth").textContent=localStorage.getItem("aiLoggedIn")==="true"?"↪ Log out":"↪ Log in"}profile.onclick=e=>{e.stopPropagation();account();pop.classList.toggle("open")};$("sidebarAuth").onclick=e=>{e.stopPropagation();if(localStorage.getItem("aiLoggedIn")==="true"){localStorage.removeItem("aiLoggedIn");account();pop.classList.remove("open")}else location.href="pages/login.html"};$("profileBtn").onclick=()=>location.href="pages/profile.html";document.addEventListener("click",e=>{if(!pop.contains(e.target)&&e.target!==profile)pop.classList.remove("open")});
document.querySelectorAll(".suggestions button").forEach(b=>b.onclick=()=>{input.value=b.dataset.msg;submit()});renderHistory();account();